# Reading different files in python:

# Contents: 

1. Reading a .txt & .dat data
2. Reading a book
3. Reading a csv (using numpy)
4. Reading a csv using Pandas
5. A basic tour of Pandas


Important note: To read this ipynb you should use Jupiter (http://nbviewer.ipython.org/github/twistedhardware/mltutorial/blob/master/notebooks/jupyter/1.Introduction.ipynb)

To make the upgrade type in a terminal:

sudo pip install --upgrade "ipython[all]"

#1. Reading a book

In [1]:
%pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


If you want to read a book we can use the python function open.
Example: We want to read the book "metamorphosis.txt" 

In [5]:
open("metamorphosis.txt", "r")

This just open the file in mode reading ("r"), but it doesn't read it. To do so use read. 


In [9]:
f = open("metamorphosis.txt", "r")
book = f.read()
#print book

I open the book and call it "f" and then I read "f" what I read is now call it book, if 
you print book you would see all the metamorphosis book. But wait, which data type is book?

In [15]:
type(book)

str

Then I can print some parts of the book like this:

In [27]:
book[100:200]

'eBook is for the use of anyone anywhere at no cost and with\r\nalmost no restrictions whatsoever.  You'

here you can read more about the open function:
https://docs.python.org/2/library/functions.html#open

In [ ]:
If you want to read line by line you can use readline:

In [31]:
f = open("metamorphosis.txt", "r")
print(f.readline()) 
print(f.readline()) 



The Project Gutenberg EBook of Metamorphosis, by Franz Kafka



In [ ]:
To read all the book then you need to loop over the lines:

In [38]:
f = open("metamorphosis.txt", "r")
book = []
for lines in f:
    book.append(lines) 

#2. Reading a .txt & .dat files

In general you don't want to read a data file line by line and off course you don't want your data as a string.
To read data numpy is you best option. There are two main function to do this (loadtxt and genfromtxt) they are similar 
but genfromtxt has more options, so we will use genfromtxt.

In [42]:
import numpy as np

In [43]:
data = np.genfromtxt("data.txt")
print data

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


In [45]:
np.shape(data) 

(4, 2)

### Exercise:

Select the x column of data.

alternatively you can use:

In [47]:
x, y = np.genfromtxt("data.txt", unpack=True)
print x, y

[ 1.  3.  5.  7.] [ 2.  4.  6.  8.]
:)


#3. Reading a .csv using (numpy)

In [49]:
data = np.genfromtxt("data.csv", delimiter=",")
print data

[[  1.   2.]
 [  3.   4.]
 [  5.   6.]
 [  7.   8.]
 [  9.  10.]]


In [57]:
data = np.genfromtxt("homicidios.1990.a.2013.csv", delimiter=",")
data[1]

array([  5.00100000e+03,              nan,              nan,
         3.92400000e+03,   1.68839400e+06,              nan,
         4.58500000e+03,   1.72176700e+06,   2.66296195e+02,
         4.12000000e+03,   1.75671100e+06,   2.34529186e+02,
         2.85200000e+03,   1.79349100e+06,   1.59019477e+02,
         2.93200000e+03,   1.83219700e+06,   1.60026460e+02,
         3.71100000e+03,   1.87224100e+06,   1.98211662e+02,
         3.82400000e+03,   1.91286000e+06,   1.99910082e+02,
         3.16900000e+03,   1.95329300e+06,   1.62238845e+02,
         2.95000000e+03,   1.99278100e+06,   1.48034330e+02,
         3.25800000e+03,   2.03056000e+06,   1.60448349e+02,
         3.15100000e+03,   2.06587100e+06,   1.52526465e+02,
         3.45600000e+03,   2.09861800e+06,   1.64679804e+02,
         3.58900000e+03,   2.12987400e+06,   1.68507621e+02,
         1.93800000e+03,   2.15960900e+06,   8.97384665e+01,
         1.07400000e+03,   2.18783100e+06,   4.90897149e+01,
         7.55000000e+02,

In [60]:
filling_values = []
for i in range(75):
    filling_values.append(999)

In [61]:
data = np.genfromtxt("homicidios.1990.a.2013.csv", delimiter=",", filling_values=filling_values)

http://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html
http://bulldog2.redlands.edu/facultyfolder/deweerd/tutorials/Tutorial-ReadingWritingData.pdf

# 4. Reading .csv using pandas

In [64]:
import pandas 
data = pandas.read_csv("homicidios.1990.a.2013.csv",parse_dates=True) 

In [66]:
print data

        cod               municipio departamento  hom90    pob90       tas90  \
0      5001                Medellín    Antioquia   3924  1688394  232.410208   
1      5002               Abejorral    Antioquia     33    24789  133.123563   
2      5004                Abriaquí    Antioquia      5     3201  156.201187   
3      5021              Alejandría    Antioquia      7     4851  144.300144   
4      5030                   Amagá    Antioquia     31    23606  131.322545   
5      5031                  Amalfi    Antioquia     25    18535  134.879957   
6      5034                   Andes    Antioquia     50    38759  129.002296   
7      5036             Angelópolis    Antioquia      8     6144  130.208333   
8      5038               Angostura    Antioquia     18    13133  137.059316   
9      5040                   Anorí    Antioquia     18    12351  145.737187   
10     5042    Santafé de Antioquia    Antioquia     28    20698  135.278771   
11     5044                    Anza    A